name: abx-exp23
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - tqdm
  - numpy
  - pytorch::pytorch
  - faiss-gpu=1.7.4
  - mkl=2021
  - blas=1.0=mkl
  - metric-learning::pytorch-metric-learning
  - pyyaml 
